server:
  port: 8080
nacos:
  config:
    server-addr: 192.168.99.33:8848
    namespace: node
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.33:8848
        namespace: node
logging:
  level:
    root: info
