server:
  port: 8080
spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 1MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: test-url-proxy
          uri: lb://platform
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: sys-url-proxy
          uri: lb://platform
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: data-url-proxy
          uri: lb://platform
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: share-url-proxy
          uri: lb://platform
          predicates:
            - Path=/share/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: swagger-url-proxy
          uri: lb://platform
          predicates:
            - Path=/platform/**
          filters:
            - StripPrefix=1
#            - BaseParam
            - Swagger
            - SysAuth
#            - SysLog

logging:
  level:
    root: debug
  config: classpath:logback-privacy.xml
