server:
  port: 8090
spring:
  application:
    name: platform
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.33:8848
        namespace: node
nacos:
  config:
    server-addr: 192.168.99.33:8848
    namespace: node
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
aj:
  captcha:
    jigsaw: classpath:images/yyjigsaw
    cache-type: redis
    water-mark: PrimiHub
    slip-offset: 5
    aes-status: true
    interference-options: 2
    req-frequency-limit-enable: true
    req-get-lock-limit: 30
    req-get-lock-seconds: 30
    req-get-minute-limit: 10
    req-check-minute-limit: 10
    req-verify-minute-limit: 10
    type: BLOCKPUZZLE


swagger2:
  enable: true
logging:
  level:
    root: info
