server:
  port: 8090
spring:
  profiles:
    active: dev
  application:
    name: platform
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 1MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        singleTaskOutput:
          destination: singlTaskChannel
        singleTaskInput:
          destination: singlTaskChannel
          group: single
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace:
nacos:
  config:
    server-addr: localhost:8848
    namespace:
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
rest:
  template:
    connection:
      connect-timeout: 30000
      read-timeout: 30000
logging:
  level:
    root: info
  config: classpath:logback-privacy.xml

